[tool.ruff]
target-version = "py312"

[tool.ruff.lint]
ignore = [
    "ANN101", # no need to annotate self
    "ANN401", # allow any
]
extend-select = [
    "ANN", # Enable the annotations rules
    "I",   # Enable the isort rules (sorts imports)
    "UP",  # Enable pyupgrade rules the keep to code up to date with the latest Python features
]

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint.per-file-ignores]
"*.ipynb" = [
    "E402", # Ignore putting imports at the top of files for notebooks => % autoreload at the top of the file.
]
"*.py" = [
    "E402", # Ignore putting imports at the top of files.
]

[tool.pyright]
typeCheckingMode = "basic"
